# 网站的基本信息
site:
  tab: RyuChan # 浏览器标签栏上显示的文本
  title: RyuChan # 网站的标题
  description: 🌸 轻盈、优雅、纯净 —— 用文字与图片记录生活与创意 # 网站的描述，用于SEO等
  language: zh  # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://shiki.style/themes
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  banner:  
    images:  
      - "https://s2.loli.net/2025/01/25/PBvHFjr5yDu6t4a.webp"  
      - "https://s2.loli.net/2025/01/25/6bKcwHZigzlM4mJ.webp"  
      - "https://s2.loli.net/2025/01/25/H9WgEK6qNTcpFiS.webp"  
      - "https://s2.loli.net/2025/01/25/njNVtuUMzxs81RI.webp"  
      - "https://s2.loli.net/2025/01/25/tozsJ8QHAjFN3Mm.webp"  
      - "https://s2.loli.net/2025/01/25/Pm89OveZq7NWUxF.webp"  
      - "https://s2.loli.net/2025/01/25/UCYKvc1ZhgPHB9m.webp"  
      - "https://s2.loli.net/2025/01/25/JjpLOW8VSmufzlA.webp"  
    height: "60vh"
  # Banner 页面标题配置
  pages:
    home:  
      title: "RyuChan's Blog"  
      subtitle: "欲买桂花同载酒，终不似，少年游！"   
      typewriterTexts: # 新增打字机文本配置  
        - "🌸 欲买桂花同载酒，终不似，少年游！"  
        - "🌸花有重开日，人无再少年！"  
        - "🌿 记录生活的点滴，分享美好的瞬间！"  
        - "📚 纸上得来终觉浅，绝知此事要躬行！" 
    friend:  
      title: "友人帐"  
      subtitle: "记录那些珍贵的友谊，分享彼此的故事"  
    about:  
      title: "About Me"  
      subtitle: "一个热爱生活与技术的普通人！" 
    navigation:  
      title: "网站导航"  
      subtitle: "收藏的常用网站和工具链接"  
    anime:
      title: "追番"  
      subtitle: "记录和分享我喜欢的动漫作品"
    project:  
      title: "Projects"  
      subtitle: "展示一些个人搭建的项目，搬运工！"
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 首页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: navigation  
      text: 导航  
      href: /navigation  
      svg: "material-symbols:explore-outline"  
      target: _self
    # - id: blog
    #   text: 博客
    #   href: /blog
    #   svg: "material-symbols:book-2-outline-rounded"
    #   target: _self
      # subItems:
      #   - id: all
      #     text: All
      #     href: /blog
      #     svg: "material-symbols:ink-pen-outline-rounded"
      #     target: _self
      #   - id: course
      #     text: 教程
      #     href: /blog/category/Course
      #     svg: "material-symbols:book-outline"
      #     target: _self
      #   - id: anime  
      #     text: 动漫  
      #     href: /blog/category/Anime  
      #     svg: "material-symbols:movie-outline"  
      #     target: _self 
      #   - id: tv  
      #     text: TV  
      #     href: /blog/category/TV  
      #     svg: "material-symbols:movie-outline"  
      #     target: _self 
      #   - id: documentation
      #     text: 文章
      #     href: /blog/category/Documentation
      #     svg: "material-symbols:unknown-document-outline-rounded"
      #     target: _self
        # - id: examples
        #   text: Examples
        #   href: /blog/category/Examples
        #   svg: "material-symbols:deployed-code-outline"
        #   target: _self
        # 子菜单项配置
    - id: anime  
      text: 追番  
      href: /anime  
      svg: "material-symbols:movie-outline"  
      target: _self 
    - id: project
      text: 项目
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 友人帐
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    # - id: contact
    #   text: Contact
    #   href: "mailto:contact.evesunmaple@outlook.com"
    #   target: _blank # 在新标签页打开
    #   svg: "material-symbols:attach-email-outline-rounded"

# 用户的个人信息
user:
  name: RyuChan # 用户名
  site: "https://hub.xiaozhangya.xin" # 用户的网站链接
  avatar: /profile.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      # - href: "https://afdian.com/a/saroprock" # 链接
      #   ariaLabel: Support my work # 图标的可访问性标签
      #   title: Support my work # 图标的悬浮标题
      #   svg: "ri:cup-line"
      - href: "https://github.com/xz131714"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/1536411565"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/xzz_ya"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
      # - href: "https://t.me/xzz_ya"
      #   ariaLabel: Telegram
      #   title: Telegram
      #   svg: "ri:telegram-line"
      - href: "https://app.folo.is/share/feeds/172229198194932736"  
        ariaLabel: Subscribe via Folo  
        title: Folo  
        svg: "ri:rss-fill"

  footer:
    social:
      # - href: "https://afdian.com/a/saroprock" # 链接
      #   ariaLabel: Support my work # 图标的可访问性标签
      #   title: Support my work # 图标的悬浮标题
      #   svg: "ri:cup-line"
      - href: "https://github.com/xz131714"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/1536411565"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/xzz_ya"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
      - href: "https://t.me/xzz_ya"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"

# 评论系统配置
comments:
  enable: true # 是否启用评论
  type: giscus # giscus/waline/none
  giscus:
    repo: "xz131714/gsc"
    repoId: "R_kgDOPTM-mA"
    category: "General"
    categoryId: "DIC_kwDOPTM-mM4CtcFq"
    mapping: "pathname"
    lang: "zh-CN"
    inputPosition: "top"
    reactionsEnabled: "1"
    emitMetadata: "0"
    loading: "lazy"
  waline:
    serverURL: "https://your-waline-server"
    lang: "zh-CN"
    emoji:
      - "https://unpkg.com/@waline/emojis@1.1.0/weibo"
      - "https://unpkg.com/@waline/emojis@1.1.0/bilibili"
    meta: ["nick", "mail", "link"]
    requiredMeta: []
    reaction: false
    pageview: false
# Umami 统计配置
umami:
  enable: true
  baseUrl: "https://um.131714.xyz"
  shareId: "a3FQfFJqDvjTVbVh"
  websiteId: "42d2e65e-b7b5-4cf0-b73d-9058a90ee2eb"
  timezone: "Asia/Shanghai"
